
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batch
    username: postgres
    password: ahmed
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    job:
      enabled: false
  application:
    name: fgbd-referenciel
server:
  port: 8083
