###################################################################################################
# Cloud-discovery Commun Properties Definition
###################################################################################################

## =================================================================================================
## Application configuration
## =================================================================================================
spring:
  http:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

## Running port
application.port: "@cloud.gateway.build.port@"

## Timeout for the gateway
gateway.timeout: 60000

## ribbon configuration
hystrix.command.default.execution.timeout.enabled: false
hystrix.shareSecurityContext: true

ribbon:
  ReadTimeout: ${gateway.timeout}
  ConnectTimeout: ${gateway.timeout}
