server:
  port: 8086
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_URI:http://knh:07454640YACINE.@localhost:8761/eureka}
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5434/fgdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

referential:
  api:
    url: http://localhost:8083/api
