spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: extract-batch-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/*
server:
    port: 8085

## Enabel Admin server client
#spring.boot.admin.client.enabled: true
eureka:
  client:
    fetchRegistry: true
