###################################################################################################
# Properties Definition for local profile 
###################################################################################################

## Override Running port
application.port: 8888

## Eureka sever param
eureka.client.service-url.defaultZone:  http://knh:07454640YACINE.@localhost:8761/eureka
